cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('listings.urls', namespace='listings'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path

from listings.views import product_list, product_detail

app_name = 'listings'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', product_detail, name='product_detail'),


]

listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
from django.urls import reverse


class Size(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=20, unique=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=20, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('listings:product_list_by_category',
                       args=[self.slug]
                       )


class Sex(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=20, unique=True)

    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Modelka(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name



class Product(models.Model):
    name = models.CharField(max_length=100)
    model = models.ForeignKey(Modelka, on_delete=models.CASCADE, related_name='product',
                              default=None)
    poster = models.ImageField(upload_to='posters/%y/%m/%d', default=None)
    slug = models.SlugField(max_length=100, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product')
    sex = models.ForeignKey(Sex, on_delete=models.CASCADE, related_name='product')
    color = models.ForeignKey(Color, on_delete=models.CASCADE, related_name='product')
    size = models.ForeignKey(Size, on_delete=models.CASCADE, related_name='product')
    price = models.DecimalField(max_digits=8, decimal_places=2)
    count = models.IntegerField()
    description = models.TextField(default=True, blank=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}: {self.model.name}"

    class Meta:
        ordering = ('-name',)
        verbose_name_plural = 'Товары'


    def get_absolute_url(self):
        return reverse(
            'listings:product_detail',
            args=[self.category.slug, self.slug]
        )

    def get_average_review_score(self):
        average_score = 0.0

        if self.reviews.count() > 0:
            total_score = sum([review.rating for review in self.reviews.all()])
            average_score = total_score / self.reviews.count()
        return round(average_score, 1)

class ImageProduct(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    img = models.ImageField(upload_to='img/%y/%m%d')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='imageproducts')

    def __str__(self):
        return self.name


class Review(models.Model):
    product = models.ForeignKey(Product, related_name='reviews',
                                on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    text = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

listings/forms.py
from django import forms
from .models import Review

REVIEW_CHOICES = [('1','1'), ('2','2'), ('3','3'), ('4','4'), ('5','5')]

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'rating']
        widgets = {
            'text': forms.Textarea(
                attrs={
                    'class': 'form-control shadow px-2',
                    'rows': 6
                }
            ),
            'rating': forms.RadioSelect
        }

listings/views.py
from django.http import HttpRequest, QueryDict, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from cart.forms import CartAddProductForm
from listings.forms import ReviewForm
from listings.models import Modelka, Category, Product, Sex, Color, Size, Review


def product_list(request, category_slug=None):
    models = Modelka.objects.all()
    categories = Category.objects.all()
    sexs = Sex.objects.all()
    colors = Color.objects.all()

    sizes = Size.objects.all()
    print("Site: ", HttpRequest.get_port(request))
    print("Path: ", HttpRequest.get_full_path(request))
    print(" absolut path: ", HttpRequest.build_absolute_uri(request, location=None))
    print("///", HttpRequest.is_secure(request))
    print("Response: ", HttpResponse.content)

    if category_slug:
        requested_category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=requested_category)
        print("yes category", request.headers.get('User-Agent'))
        #print("Cocie: ", request.get_signed_cookie('name'))
        if request.user.is_authenticated:
            print("User")
        else:
            print("Not user")
    else:
        requested_category = None
        products = Product.objects.all()
        print('Not category', request.headers)
    return render(
        request,
        'product/list.html',
        {
            'models': models,
            'categories': categories,
            'sexs': sexs,
            'colors': colors,
            'sizes': sizes,
            'products': products,
            'requested_category': requested_category,
        }
    )


def product_detail(request, category_slug, product_slug):
    category = get_object_or_404(Category, slug=category_slug)
    product = get_object_or_404(
        Product,
        category_id = category.id,
        slug=product_slug
    )
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            cf = review_form.cleaned_data
            author_name = "Anonymous"
            Review.objects.create(
                product=product,
                author=author_name,
                rating=cf['rating'],
                text=cf['text']
            )

        return redirect(
            'listings:product_detail',
            category_slug=category_slug, product_slug=product_slug)
    else:
        review_form = ReviewForm()
        cart_product_form = CartAddProductForm()

    return render(
        request, 'product/detail.html',
        {
            'product': product,
            'review_form': review_form,
            'cart_production_form': cart_product_form,
        }
    )

listings/templates/product/detail.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="card shadow-custom border-0 col-lg-8 mx-auto">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <img src="{{ product.poster.url }}" alt="" class="img-fluid rounded-0">
        </div>
        <div class="col-lg-6">
            <div class="top">
                <h2 class="mt-4 font-weight-bold text-grey">
                        {{ product.name }}
                </h2>
                <h3 class="mt-3 text-grey">
                    Модель:{{ product.model }}
                </h3>
            <div>
                <span class="font-weight-bold text-grey">
                    Цвет:
                </span> {{ product.color }}
            </div>
            <div>
                <span class="font-weight-bold text-grey">
                    Размер:
                </span> {{ product.size }}
            </div>
        </div>


            {% if product.available %}
                <div class="alert alert-success my-3 text-center">
                    Available
                </div>
            {% else %}
                <div class="alert alert-danger my-3 text-center">
                    Currently unavailable
                </div>
            {% endif %}
        <hr>
                <div class="review">
                    <span class="font-weight-bold text-grey">
                        Average rating: {{ product.get_average_review_score }}/5.0
                    </span>
                <div class="mb-3 font-weight-bold">
                <a href="" class="text-warning" data-toggle="modal"
                data-target="#myModal">
                    Write review
                </a>
                </div>
            </div>
    <div class="mb-4">
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {% csrf_token %}
            <span class="input-group add-to-cart shadow-custom">
                <div class="input-group-prepend">
            <span class="input-group-text
                font-weight-bold px-3 btn btn-block price">
                ${{ product.price }}
            </span>
                </div>
            <span id="minus" class="input-group-text button_minus px-4">
            ----
            </span>
           -=-{{ cart_product_form.quantity }}
            <span id="plus" class="input-group-text button_plus px-4">
           ++++
            </span>
            <div class="input-group-append">
            <button class="btn btn-danger px-4 reduce_padding"
                type="submit" data-toggle="tooltip"
                    data-placement="top" title="Add to cart">
                <i class="fas fa-shopping-cart"></i>
            </button>
        </div>
        </span>
</form>
</div>
</div>
</div>
</div>

<div>
    <span class="font-weight-bold text-grey">
        Сведения о товаре:
    </span> {{ product.description }}
</div>
</div>
<hr class="col-7 mx-auto">
<div class="card shadow-custom border-0 col-lg-8 mx-auto mb-3">
<h3 class="py-2 text-grey">Reviews:</h3>
{% for review in product.reviews.all %}
<span class="font-weight-bold py-2 text-grey">
{{ review.author }} - {{ review.rating }}/5 - {{ review.created }}
</span>
<span class="text-justify pb-2">
{{ review.text }}
</span>
<hr>
{% empty %}
<span class="pb-2">Currently no reviews</span>
{% endfor %}
</div>
<!-- MODAL -->
<div class="modal" id="myModal">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<h5 class="modal-title">Write your review</h5>
<button class="close" data-dismiss="modal">&times;</button>
</div>
<form method="post">
    {% csrf_token %}
<div class="modal-body">
<div class="bg-grey">
<div class="text-center pt-2">
Rating:
<div id="full-stars" class="d-inline text-center">
<div class="rating-group">
<label class="rating__label" for="id_rating_0">
<i class="rating__icon rating__icon--star fa fa-star"></i>
</label>
<input class="rating__input" name="rating"
id="id_rating_0" value="1" type="radio" required>
<label class="rating__label" for="id_rating_1">
<i class="rating__icon rating__icon--star fa fa-star"></i>
</label>
<input class="rating__input" name="rating"
id="id_rating_1" value="2" type="radio" required>
<label class="rating__label" for="id_rating_2">
<i class="rating__icon rating__icon--star fa fa-star"></i>
</label>
<input class="rating__input" name="rating"
id="id_rating_2" value="3" type="radio" required>
<label class="rating__label" for="id_rating_3">
<i class="rating__icon rating__icon--star fa fa-star"></i>
</label>
<input class="rating__input" name="rating"
id="id_rating_3" value="4" type="radio" required>
<label class="rating__label" for="id_rating_4">
<i class="rating__icon rating__icon--star fa fa-star"></i>
</label>
<input class="rating__input" name="rating" checked
id="id_rating_4" value="5" type="radio" required>
</div>
</div>
</div>
<hr class="m-0">
<div class="input-field text-center p-2">
{{ review_form.text}}
</div>
</div>
</div>
<div class="modal-footer">
<button class="btn btn-danger" type="submit">Confirm</button>
</div>
</form>
</div>
</div>
</div>
{% endblock content %}

listings/templates/product/list.html
{% extends 'base.html' %}

{% block title %}Nike ltd.{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-3">
            <div class="card shadow-custom border-0">
                <h4 class="p-3 font-weight-bold text-grey">
                    Категории
                </h4>
    <ul class="list-group border-0 categories_list">
        <li
                {% if not requested_category %}
                    class="list-group-item border-0 p-0 selected"
                {% else %}
                    class="list-group-item border-0 p-0 unselected"
                {% endif %}>
                    <a href="{% url 'listings:product_list' %}"
                    class="btn btn-block text-left">All</a>
        </li>
    {% for category in categories %}
        <li
            {% if category.slug == requested_category.slug %}
                    class="list-group-item border-0 p-0 selected"
            {% else %}
                    class="list-group-item border-0 p-0 unselected"
            {% endif %}>
            <a href="{{ category.get_absolute_url }}" class="btn btn-block text-left">{{ category.name }}</a>
        </li>
    {% endfor %}
    </ul>
    </div>
</div>
<div class="col-lg-6">
    <div class="card shadow-custom border-0 mb-4">
        <div class="card-body text-center">
            <h2 class="font-weight-bold text-grey">
               {% if requested_category %}
                    {{ requested_category.name }}
                {% else %}
                    Our products
                {% endif %}
            </h2>
                <div class="bottom_line"></div>
                </div>
        </div>
    <div class="row no-gutters">
        {% for product in products %}
        <div class="col-sm-6">
        <div class="card product">
        <div class="item">
            <div class="item-image">
        <a href="{{ product.get_absolute_url }}"> <img src="{{ product.poster.url }}" alt=""
        class="img-fluid rounded-0"></a>
        </div>
        <div class="item-text">
        <div class="item-text-wrap">
        <a href="{{ product.get_absolute_url }}" class="h2 text-white text-decoration-none">
        <i class="fas fa-search-plus"></i>
        </a>
        </div>
        </div>
        <div class="card-body text-center">
            {{ product.name }}
        <hr>
            <span>{{ product.price }} руб.</span>
        <div>
        <i class="fas fa-fire"></i> Модель:{{ product.model }}
        </div>
    </div>
</div>
</div>
</div>
        {% endfor %}
</div>
</div>
<div class="col-lg-3"></div>
</div>
<hr>
{% endblock content %}